from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://google.com')
searchbox = driver.find_element_by_xpath('//*[@id="tsf"]/div[2]/div[1]/div[1]/div/div[2]/input')
searchbox.send_keys('mycamu.co.in')
searchbox.submit()
searchButton=driver.find_element_by_xpath('//*[@id="rso"]/div[1]/div/div/div[1]/a/div/cite')
searchButton.click()
searchLink=driver.find_element_by_xpath('//*[@id="username"]')
searchLink.send_keys('yasicarajesh@gmail.com')
searchPassword=driver.find_element_by_xpath('//*[@id="password"]')
searchPassword.send_keys('211986153')
searchLogin=driver.find_element_by_xpath('//*[@id="login_tab"]/div[1]/form/div[3]/button')
searchLogin.click()
searchTask=driver.find_element_by_xpath('//*[@id="stud_home_main"]/div/div[1]')
searchTask.click()
searchBar=driver.find_element_by_xpath('//*[@id="ExmSch"]/div[1]/div[1]/div[1]/div[1]/div/header')
searchBar.click()
